
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    language: 'nl'

#####
# Start of custom configuration
#####

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

# Light groups
light:
  - platform: group
    name: Keuken slimme lichten
    entities:
      - light.slim_keuken
      - light.slim_spots_aanrecht
      - light.slim_spots_eetkamer_keuken
  - platform: group
    name: Keuken midden
    entities:
      - light.keuken_midden_1
      - light.keuken_midden_2
  - platform: group
    name: Keuken aanrecht
    entities:
      - light.keuken_aanrecht_1
      - light.keuken_aanrecht_2
  - platform: group
    name: Keuken gootsteen
    entities:
      - light.keuken_gootsteen_1
      - light.keuken_gootsteen_2
  - platform: group
    name: Keuken - eetkamer
    entities:
      - light.keuken_eetkamer_1
      - light.keuken_eetkamer_2
      - light.keuken_eetkamer_3
  - platform: group
    name: Keuken alles
    entities:
      - light.keuken_midden_1
      - light.keuken_midden_2
      - light.keuken_aanrecht_1
      - light.keuken_aanrecht_2
      - light.keuken_gootsteen_1
      - light.keuken_gootsteen_2
      - light.keuken_eetkamer_1
      - light.keuken_eetkamer_2
      - light.keuken_eetkamer_3
      # Note: not a smart light, this is the dobiss light
      - light.toog
      
  - platform: group
    name: Terras
    entities:
      - light.terras_links_boven
      - light.terras_links_onder
      - light.terras_rechts_boven
      - light.terras_rechts_onder

# Dobiss Home Automation
  #- platform: dobiss
  #  host: 192.168.1.116
  #  port: 10001
    #scan_interval: 10 # Note: lights behaved very weird once not long after enabling this, so...

# dobiss:
#   host: 192.168.1.116
#   port: 10001

# Smappee
smappee:
  #host: 192.168.1.128
  client_id: !secret smappee_client_id
  client_secret: !secret smappee_client_secret

# Afvalbeheer
sensor:
    - platform: afvalbeheer
      wastecollector: Limburg.NET
      resources:
        - grofvuil
        - houtafval
        - keukenafval
        - papier
        - plastics
        - pmd
        - restafval
        - textiel
        - tuinafval
        - tuinbak
      postcode: 3920
      streetname: Molenstraat
      streetnumber: 38
      cityname: Lommel
      printwastetypes: 1
      upcomingsensor: 1
      dutch: 1

# Enable debug logging
logger:
  default: warning
  logs:
    custom_components.dobiss: debug

#####
# End of custom configuration
#####

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
