# Services for Dobiss Domotics

# Service ID
importInstallation:
  # Service name as shown in UI
  name: Import Dobiss installation
  # Description of the service
  description: Refreshes the imported Dobiss Domotics installation.
